version: '3.8'

services:
  data-collector:
    build: .
    container_name: tuya-data-collector
    restart: always
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: python collector/data_collector.py

  api:
    build: .
    container_name: sarimax-api
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    command: uvicorn api.index:app --host 0.0.0.0 --port 8000
  # For local development on Windows, we can uncomment this to have a local DB
  # mongodb:
  #   image: mongo:latest
  #   container_name: sarimax-mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

volumes:
  mongodb_data:
